#!/bin/bash
export MXE=/usr/lib/mxe
export TARGET=x86_64-w64-mingw32.static
export PATH="$MXE/usr/bin:$PATH"

#make -C "$MXE" -j"$(nproc)" MXE_TARGETS="$TARGET" \
#  pkgconf cmake ninja nasm yasm aom x265

cd /tmp
wget -q https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n7.0.3.tar.gz -O ffmpeg-7.0.3.tar.gz
tar xzf ffmpeg-7.0.3.tar.gz
cd FFmpeg-n7.0.3

export CC=$TARGET-gcc CXX=$TARGET-g++ AR=$TARGET-ar LD=$TARGET-ld STRIP=$TARGET-strip RANLIB=$TARGET-ranlib WINDRES=$TARGET-windres
export PKG_CONFIG=pkg-config
export PKG_CONFIG_PATH="$MXE/usr/$TARGET/lib/pkgconfig:$MXE/usr/$TARGET/share/pkgconfig"
export PKG_CONFIG_LIBDIR="$PKG_CONFIG_PATH"
PREFIX=$MXE/usr/$TARGET
PKGDIR="$PREFIX/lib/pkgconfig"
#  --extra-ldflags="-L$MXE/usr/$TARGET/lib -static" \

eval ./configure \
  --prefix="$PREFIX" \
  --pkgconfigdir="$PKGDIR" \
  --arch=x86_64 --target-os=mingw32 --cross-prefix=$TARGET- \
  --pkg-config-flags=--static \
  --extra-cflags="-I$MXE/usr/$TARGET/include" \
  --extra-ldflags=-static \
  --enable-static --disable-shared --disable-debug --enable-pic \
  --disable-librsvg --disable-xlib --disable-libxcb --disable-sdl2 \
  --disable-vulkan --disable-opencl --disable-libdrm \
  --disable-autodetect \
  --disable-programs --disable-doc \
  --disable-everything \
  --enable-network \
  --enable-protocol=file,pipe,tcp,udp,rtp,rtsp,tls,https \
  --enable-demuxer=rtsp,sdp,rtp \
  --enable-decoder=h264,hevc,mpeg4,mjpeg,aac,pcm_alaw,pcm_mulaw,opus \
  --enable-parser=h264,hevc,aac,mpeg4video,mjpeg,opus \
  --enable-bsf=h264_mp4toannexb,hevc_mp4toannexb,aac_adtstoasc \
  --enable-swscale --enable-swresample \
  --enable-libx265 --enable-gpl

make -j"$(nproc)"
make install
